Add default read offsets for Node Buffer compatibility
rvagg/bl pull request #99
Opened 2021-02-07 04:58 UTC by benallfree

This PR adds an optional offset to the `readXX` methods to create compatibility with the Node Buffer API https://nodejs.org/api/buffer.html#buffer_buf_readbigint64be_offset

2021-02-07 10:22 UTC, mcollina requested changes
could you please add a unit test? Thanks!

2021-02-08 00:40 UTC, benallfree commented
@mcollina Hey ok I added some tests. Please check out how I handled the floats, I kind of feel like this is a better test anyway. Rather than testing against hard-coded hex values, we can test equivalence with the output value of a real Node Buffer for the same input. If you agree that this is a better test, I'm happy to update the rest of the `read*` tests to match. Please let me know! :)

2021-02-08 09:23 UTC, mcollina approved these changes
lgtm

2021-02-09 03:09 UTC, rvagg approved these changes
sure, I don't think this is a breaking change in any way, so just a semver-minor?

2021-02-09 03:37 UTC, benallfree commented
@rvagg agree

Did you want me to update the `readXX` tests to test against a native `Buffer` output rather than hard-coded values?

2021-02-09 10:36 UTC, merged